[package]
name = "openarmor-tray"
version = "0.1.0"
edition = "2021"

[dependencies]
tray-item = "*"
windows = { version = "0.58.0", features = ["Data_Xml_Dom", "UI_Notifications", "Win32_Foundation"] }

[build-dependencies]
windres = "*"
