[package]
name = "openarmor-tray"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tray-item = "*"
winrt-notification = "0.5.0"

[build-dependencies]
windres = "*"
